/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TwoDMagicArray;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  public void tests() {
    int[][] a = {
        {1,1},
        {1,1}
    };
    int[][] b = {
        {4,9,2},
        {3,5,7},
        {8,1,6}
    };
    int[][] c = {
        {3,1,2},
        {3,1,1}
    };
    int[][] d = {
        {1,1,1},
        {2,2,2},
        {3,3,3}
    };
    int[][] e = {
        {16,3,2,13},
        {5,10,11,8},
        {9,6,7,12},
        {4,15,14,1}
    };
    assertEquals(true,App.isMagic(a));
    assertEquals(true,App.isMagic(b));
    assertEquals(false,App.isMagic(c));
    assertEquals(false,App.isMagic(d));
    assertEquals(true,App.isMagic(e));
  }
}
